(source gnu)
(source marmalade)
(source melpa)

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "enh-ruby-mode")
(depends-on "magit")
(depends-on "monokai-theme")
(depends-on "pallet")
(depends-on "robe")
(depends-on "rvm")
