(source gnu)
(source marmalade)
(source melpa)

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "dash")
(depends-on "enh-ruby-mode")
(depends-on "git-commit")
(depends-on "inf-ruby")
(depends-on "magit")
(depends-on "magit-popup")
(depends-on "monokai-theme")
(depends-on "pallet")
(depends-on "robe")
(depends-on "rvm")
(depends-on "with-editor")
