#+PROPERTY: header-args :tangle yes

* Config

** Basics


This is an emacs configuration written as Org file(s). Literate configs are a
side of literate programming
(https://en.wikipedia.org/wiki/Literate_programming) where configuration is
written in a file along with its documentation. From this literate configuration
file, configs applied are subject to be extracted into a "runnable" file (in
this case into init.el), this process is called "tangling" (important Org
functions for this are org-babel-tangle and org-babel-tangle-file, see:
https://orgmode.org/manual/Extracting-source-code.html for more info on the
subject).

*** Basic defaults

Regarding setting defaults and/or customizations, read this first:

https://macowners.club/posts/setq-vs-customize-set-variable/

Miscellaneous defaults below

#+begin_src emacs-lisp
(savehist-mode 1)              ;; Save history typed in minibuffer
(global-auto-revert-mode 1)

;; Explicit mode enabling via function calls ---
(menu-bar-mode -1)
(tool-bar-mode -1)
(blink-cursor-mode -1)
(global-display-line-numbers-mode 1)


(setq
  auth-source-save-behavior nil
  backup-by-copying t
  browse-url-browser-function 'browse-url-firefox
  completions-detailed t
  confirm-kill-emacs 'y-or-n-p
  confirm-nonexistent-file-or-buffer nil
  create-lockfiles nil
  delete-old-versions t
  dired-kill-when-opening-new-dired-buffer t
  display-time-default-load-average nil
  fill-column 80
  ibuffer-expert t
  ibuffer-show-empty-filter-groups nil
  indent-tabs-mode nil
  inhibit-startup-screen t
  initial-scratch-message nil
  kept-new-versions 3
  kept-old-versions 2
  native-comp-async-report-warnings-errors nil
  package-native-compile t
  package-selected-packages nil
  scroll-conservatively 0
  scroll-down-aggressively 0.01
  scroll-margin 1
  scroll-up-aggressively 0.01
  show-paren-delay 0
  use-short-answers t
  vc-follow-symlinks t
  version-control t
  window-combination-resize t
  xref-search-program 'ripgrep)

(add-hook 'window-setup-hook
          (lambda ()
            (scroll-bar-mode -1) ;; reliably disable scroll bar
            (cua-mode 1)))       ;; reliably enable CUA mode
#+end_src

Some miscellaneous defaults, but set in a different manner

#+BEGIN_SRC emacs-lisp
(setq-default visible-bell nil                        ;; No shaking
              select-enable-clipboard t               ;; Unite Emacs & system clipboard
              line-number-mode t                      ;; Line number
              debug-on-error nil
              horizontal-scroll-bar-mode nil
              column-number-mode t
              global-prettify-symbols-mode t)
#+END_SRC

UTF-8 everywhere, because it is the standard and disable CJK
coding/encoding (Chinese/Japanese/Korean characters).

#+BEGIN_SRC emacs-lisp
(setq utf-translate-cjk-mode nil
      default-file-name-coding-system 'utf-8
      locale-coding-system 'utf-8
      x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING))

(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-language-environment 'utf-8)
(setenv "LC_CTYPE" "en_US.UTF-8")
(setenv "LC_ALL" "en_US.UTF-8")
(setenv "LSP_USE_PLISTS" "true")
(setq lsp-use-plists t)

(if (boundp buffer-file-coding-system)
    (setq buffer-file-coding-system 'utf-8)
  (setq default-buffer-file-coding-system 'utf-8))
#+END_SRC

Performance tweak from [[https://emacs-lsp.github.io/lsp-mode/page/performance/][here]].
#+begin_src emacs-lisp
(setq read-process-output-max (* 30 1024 1024)) ;; 30mb
(setq gc-cons-threshold 1000000000)
#+end_src


*** Theme

Use `monokai` theme for Emacs.

#+BEGIN_SRC emacs-lisp
(use-package monokai-theme
  :ensure t
  :init
  (load-theme 'monokai t))
#+END_SRC

Set my preferred font, as well as stronger highlight for search results.
Selected by listing the faces (M-x list-faces-display, and then
searching for 'lazy-highlight', which corresponds to the
search results for a given ISearch.

Make sure to install "Nerd Font" set from
https://www.nerdfonts.com/font-downloads

#+begin_src emacs-lisp
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#272822" :foreground "#F8F8F2" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 140 :width normal :foundry "PfEd" :family "InconsolataGo Nerd Font Mono"))))
 '(italic ((t (:underline nil))))
 '(lazy-highlight ((t (:inherit highlight :background "DarkGoldenrod1")))))
#+end_src

#+begin_src emacs-lisp
(setq custom-safe-themes
 '("37c8c2817010e59734fe1f9302a7e6a2b5e8cc648cf6a6cc8b85f3bf17fececf" default)
 )
#+end_src

Increase text size on Mac OS X (Macbook Air )

#+begin_src emacs-lisp
(if (eq system-type 'darwin)
  (set-face-attribute 'default nil :height 140))
#+end_src


*** Column enforce mode
Because 80 columns is THE
rule. https://www.kernel.org/doc/Documentation/process/coding-style.rst

#+begin_src emacs-lisp
;; Enable fill column indicator only in programming-related buffers
(defun enable-fill-column-indicator-in-prog-mode ()
  "Enable fill column indicator in programming-related buffers."
  (display-fill-column-indicator-mode 1))

(custom-set-variables
 '(global-display-fill-column-indicator-mode nil)
)
;; Add the hook to programming-related modes
(add-hook 'prog-mode-hook 'enable-fill-column-indicator-in-prog-mode)
#+end_src


*** OS customizations
**** Mac keys

The variables available for binding the modifier keys on Mac keyboards are the following:

- mac-function-modifier
- mac-control-modifier
- mac-command-modifier
- mac-option-modifier
- mac-right-command
- mac-right-control-modifier
- mac-right-option-modifier

The values can be `'control`, `'alt`, `'meta`, `'super`, `'hyper` or `nil` (setting to nil allows the OS to assign values). Sources: [[https://www.emacswiki.org/emacs/EmacsForMacOS#toc31][emacswiki.org]] 
[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Mac-_002f-GNUstep-Events.html#Mac-_002f-GNUstep-Events][gnu.org]].

#+begin_src emacs-lisp
(if (eq system-type 'darwin)
    (progn
    (setq-default mac-command-modifier 'meta                        ; Map Meta to Cmd
                  mac-option-modifier nil                           ; Don't use Option key
                  mac-right-option-modifier nil                     ; Disable the right Alt key
                  dired-use-ls-dired nil)))                         ; macOS command ls doesn't support --dired option
#+end_src


*** Backups

As default write backup files on ~/.emacs.d/backup, auto-save files on
~/.emacs.d/auto-save-list, and disables lock files.

#+BEGIN_SRC emacs-lisp
(let ((backup-dir "~/.emacs.d/backup/")
      (auto-saves-dir "~/.emacs.d/auto-save-list/"))
  (dolist (dir (list backup-dir auto-saves-dir))
    (when (not (file-directory-p dir))
      (make-directory dir t)))
  (setq backup-directory-alist `(("." . ,backup-dir))
        auto-save-file-name-transforms `((".*" ,auto-saves-dir t))
        tramp-backup-directory-alist `((".*" . ,backup-dir))
        tramp-auto-save-directory auto-saves-dir))
#+END_SRC

Disable backups for sensitive information. Taken from [[https://anirudhsasikumar.net/blog/2005.01.21.html][here]].

#+begin_src emacs-lisp
(define-minor-mode sensitive-mode
  "For sensitive files like password lists.
It disables backup creation and auto saving.

With no argument, this command toggles the mode.
Non-null prefix argument turns on the mode.
Null prefix argument turns off the mode."
  :init-value nil                      ;; The initial value.
  :lighter " Sensitive"                ;; The indicator for the mode line.
  :keymap nil                          ;; The minor mode bindings.
  (if sensitive-mode                   ;; Use the minor mode variable directly.
      (progn
        ;; disable backups
        (set (make-local-variable 'backup-inhibited) t)
        ;; disable auto-save
        (if auto-save-default
            (auto-save-mode -1)))
    ;; Resort to default value of backup-inhibited
    (kill-local-variable 'backup-inhibited)
    ;; Resort to default auto save setting
    (if auto-save-default
        (auto-save-mode 1))))
#+end_src

Disable for all gpg and pass edits

#+begin_src emacs-lisp
(setq auto-mode-alist
 (append '(("\\.gpg$" . sensitive-mode)
           ("!dev!shm!pass.*" . sensitive-mode))
               auto-mode-alist))
#+end_src

*** Filter marked packages from Packages buffer.

#+begin_src emacs-lisp
(defun package-menu-find-marks ()
  "Search for packages marked for action in the *Packages* buffer.
Marks are indicated by lines starting with an uppercase letter."
  (interactive)
  (occur "^[A-Z]"))

;; Bind the function to the "a" key in `package-menu-mode-map`
(define-key package-menu-mode-map (kbd "a") #'package-menu-find-marks)
#+end_src


*** Reload config

Reloads Emacs config without having to restart the service.

#+begin_src emacs-lisp
(defun emacs-reload ()
  "Reload Emacs config."
  (interactive)
  (org-babel-load-file (expand-file-name "config.org" user-emacs-directory)))
#+end_src


*** Bug hunting on Emacs init file

Very basic, but gets the job done nicely. See https://github.com/Malabarba/elisp-bug-hunter

#+begin_src emacs-lisp
(use-package bug-hunter
  :ensure t)
#+end_src


** Languages / frameworks

*** JSON
--> Handled with Treesitter.
*** Dot

#+begin_src emacs-lisp
(use-package dot-mode
  :ensure t
  :mode "\\.dot$")
#+end_src

*** gnuplot

#+begin_src emacs-lisp
(use-package gnuplot
  :ensure t
  :mode (("\\.g\\'" . gnuplot-mode)
         ("\\.p\\'" . gnuplot-mode)))
#+end_src

*** Docker
--> Handled with Treesitter.
*** HTML
--> Handled with Treesitter.
*** Markdown

Install `pandoc` package with your package manager:

#+BEGIN_SRC emacs-lisp
(use-package markdown-mode
  :ensure t
  :mode (("INSTALL\\'" . markdown-mode)
         ("CONTRIBUTORS\\'" . markdown-mode)
         ("LICENSE\\'" . markdown-mode)
         ("README\\'" . markdown-mode)
         ("\\.markdown\\'" . markdown-mode)
         ("\\.md\\'" . markdown-mode))
  :hook (markdown-mode . auto-fill-mode)
  :config
  (setq-default markdown-asymmetric-header t
                markdown-split-window-direction 'right
                markdown-command "/usr/bin/pandoc"))
#+END_SRC

Github flavored Markdown. Org-mode files can then be exported with `M-x
org-gfm-export-to-markdown`. Source: https://github.com/larstvei/ox-gfm

#+begin_src emacs-lisp
(use-package ox-gfm
  :ensure t
  :after org)
#+end_src

*** YAML
--> Handled with Treesitter.
*** CSV

#+BEGIN_SRC emacs-lisp
(use-package csv-mode
  :no-require
  :mode "\\.[CcTt][Ss][Vv]$"
  :init (setq csv-separators '("," ";" "|" " ")))
#+END_SRC

*** Ruby

Controlled by LSP and direnv

- Create a folder and drop .ruby-version and .ruby-gemset with the
  desired Ruby version and gemset to use.
- Create a .envrc with the following:

#+begin_src
source "$HOME/.rvm/scripts/rvm"
rvm use
#+end_src

- Make sure to install ruby-lsp

#+begin_src
gem install ruby-lsp
#+end_src

#+begin_src emacs-lisp
(use-package ruby-mode
  :ensure t
  :hook
  ((ruby-ts-mode . (lambda ()
                     (setq-local ruby-insert-encoding-magic-comment nil
                                 ruby-indent-tabs-mode nil
                                 tab-width 2)
                     (add-hook 'before-save-hook #'lsp-format-buffer nil t)))))
#+end_src

*** Javascript/Typescript

Below, some basic instructions to work with Javascript/Typescript projects:

- Install NVM
- Before opening a project/subfolder containing a Javascript codebase do:
- $ cd <folder>/
- $ nvm use
- $ npm i -g typescript-language-server && npm i -g typescript && npm i -g prettier
- $ yarn install

The above will ensure Emacs has the path is set and NVM_BIN points to the
correct location. After that, the following major and minor mode configs should
take care of the rest.

The below takes care of running prettier:

#+begin_src emacs-lisp
(use-package typescript-mode
  :ensure t
  :hook ((typescript-ts-mode
          tsx-ts-mode
          js-ts-mode)
         . (lambda ()
             (setq-local tab-width 2
                         indent-tabs-mode nil
                         typescript-indent-level 2
                         js-indent-level 2))))
#+end_src

#+begin_src emacs-lisp
(use-package prettier-js
  :ensure t
  :hook ((typescript-ts-mode
          tsx-ts-mode
          js-ts-mode) . prettier-js-mode))
#+end_src

--> For the rest of JS/TS config, see Treesitter and LSP sections.

*** Vue

Use Vue mode when dealing with Vue services. Note that an LSP + Treesiter setup
is possible, but I preferred not to use LSP as with _very old_  (read,
discontinued versions) of Vue, LSP would break.

Due to the above explained, use vue-mode and prettier, no completion is possible
as of today.

#+begin_src emacs-lisp
(use-package vue-mode
  :ensure t
  :mode "\\.vue\\'"
  :hook (vue-mode . prettier-js-mode))
#+end_src

*** LSP

Below, the configuration for LSP, reworked to work with treesitter modes.

Note that a few clients are disabled as back when the original LSP configuration
was put together, the performance and/or functionalities were not optimal (and
other implementations worked better). Feel free to explore if the
implementations have improved by removing them from the lsp-disabled-clients
alist and setting them up.

Completion framework is controlled by lsp-completion-provider.

#+begin_src emacs-lisp               
(use-package lsp-mode
  :ensure t
  :hook ((lsp-mode . lsp-enable-which-key-integration)
        ((ruby-ts-mode
         elixir-ts-mode
         typescript-ts-mode
         tsx-ts-mode
         js-ts-mode) . lsp-deferred))
  :commands lsp lsp-deferred
  :diminish "LSP"
  :custom
    ;; For Terraform, don't use tfls, but use Hashicorp's official implementation
    (lsp-disabled-clients '(vue-semantic-server angular-ls deno tfls credo-language-server semgrep))
    (lsp-keymap-prefix "C-l")           ; Prefix for LSP actions
    (lsp-diagnostics-provider :flycheck)
    (lsp-prefer-flymake nil)
    (lsp-session-file (locate-user-emacs-file ".lsp-session"))
    (lsp-log-io nil)                      ; IMPORTANT! Use only for debugging! Drastically affects performance
    (lsp-keep-workspace-alive nil)        ; Close LSP server if all project buffers are closed
    (lsp-idle-delay 0.7)                ; Debounce timer for `after-change-function'
    ;; core
    (lsp-enable-xref t)                   ; Use xref to find references
    (lsp-auto-configure t)                ; Used to decide between current active servers
    (lsp-auto-guess-root t)
    (lsp-enable-dap-auto-configure t)     ; Debug support
    (lsp-enable-file-watchers nil)
    (lsp-enable-imenu nil)
    (lsp-enable-indentation nil)              ; Use prettifier
    (lsp-enable-links nil)                    ; No need since we have `browse-url'
    (lsp-enable-on-type-formatting nil)       ; Prettier handles this
    (lsp-enable-suggest-server-download nil)  ; Don't prompt to download server
    (lsp-enable-symbol-highlighting t)        ; Shows usages of symbol at point in the current buffer
    (lsp-enable-text-document-color nil)      ; This is Treesitter's job
    ;; completion
    (lsp-completion-provider :capf)
    (lsp-completion-enable t)
    (lsp-completion-enable-additional-text-edit t) ; Ex: auto-insert an import for a completion candidate
    (lsp-completion-show-kind t)
    (lsp-completion-show-detail t)
    (lsp-enable-snippet t)                         ; Important to provide full JSX completion
    ;; headerline
    (lsp-headerline-breadcrumb-enable t)                  ; Optional, I like the breadcrumbs
    (lsp-headerline-breadcrumb-enable-diagnostics nil)    ; Don't make them red, too noisy
    (lsp-headerline-breadcrumb-enable-symbol-numbers t)
    (lsp-headerline-breadcrumb-icons-enable t)
    ;; modeline
    (lsp-modeline-code-actions-enable nil)        ; Modeline should be relatively clean
    (lsp-modeline-diagnostics-enable nil)         ; Already supported through `flycheck'
    (lsp-modeline-code-action-icons-enable t)
    (lsp-signature-auto-activate nil)         ; Don't show signature in modeline
    (lsp-signature-doc-lines 1)                   ; Don't raise the echo area. It's distracting
    ;; eldoc
    (lsp-eldoc-render-all nil)
    (lsp-eldoc-enable-hover nil)
    ;; lens
    (lsp-lens-enable nil)
    ;; semantic
    (lsp-semantic-tokens-enable nil)              ; Related to highlighting, and we defer to treesitter
    ;; Vue.js only
    (lsp-vetur-format-default-formatter-css "none")
    (lsp-vetur-format-default-formatter-html "none")
    (lsp-vetur-format-default-formatter-js "none")
    (lsp-vetur-validation-template nil)
    ;; Typescript / Javascript
    (lsp-clients-typescript-server "typescript-language-server")
    (lsp-clients-typescript-max-ts-server-memory 8192)
    (lsp-clients-typescript-server-args '("--stdio"))
    (lsp-typescript-suggestion-actions-enabled nil)
    (lsp-javascript-suggestion-actions-enabled nil)
    (lsp-typescript-suggest-complete-function-calls t)
    (lsp-javascript-suggest-complete-function-calls t)
    (lsp-typescript-suggest-complete-js-docs nil)
    (lsp-javascript-suggest-complete-js-docs nil)
    (lsp-typescript-surveys-enabled nil)
    ;; Elixir
    (lsp-elixir-server-command `(,(expand-file-name "~/.local/share/elixir-ls/release/language_server.sh")))
    (lsp-elixir-dialyzer-enabled nil)
    (lsp-elixir-fetch-deps t)
    ;; Ruby
    (lsp-ruby-lsp-server-command '("ruby-lsp"))
    (lsp-ruby-lsp-use-bundler nil)
  :init
    ;; Initiate https://github.com/blahgeek/emacs-lsp-booster for performance
    (advice-add (if (progn (require 'json)
                           (fboundp 'json-parse-buffer))
                    'json-parse-buffer
                  'json-read)
                :around
                #'lsp-booster--advice-json-parse)
    (advice-add 'lsp-resolve-final-command :around #'lsp-booster--advice-final-command)
  :preface
    (defun lsp-booster--advice-json-parse (old-fn &rest args)
      "Try to parse bytecode instead of json."
      (or
       (when (equal (following-char) ?#)

         (let ((bytecode (read (current-buffer))))
           (when (byte-code-function-p bytecode)
             (funcall bytecode))))
       (apply old-fn args)))
    (defun lsp-booster--advice-final-command (old-fn cmd &optional test?)
      "Prepend emacs-lsp-booster command to lsp CMD."
      (let ((orig-result (funcall old-fn cmd test?)))
        (if (and (not test?)                             ;; for check lsp-server-present?
                 (not (file-remote-p default-directory)) ;; see lsp-resolve-final-command, it would add extra shell wrapper
                 lsp-use-plists
                 (not (functionp 'json-rpc-connection))  ;; native json-rpc
                 (executable-find "emacs-lsp-booster"))
            (progn
              (message "Using emacs-lsp-booster for %s!" orig-result)
              (cons "emacs-lsp-booster" orig-result))
          orig-result))))

(with-eval-after-load 'lsp-mode
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]workbench/work/resq/infrastructure/\\'")
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]workbench/work/resq/ecs/\\'")
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]workbench/work/resq/apps/resq-main/public/.*[/\\\\]bundle\\'")
)
#+end_src

LSP UI for all nice IDE-like overlays of documentation

#+begin_src emacs-lisp
(use-package lsp-ui
  :ensure t
  :commands lsp-ui-mode
  :bind (:map lsp-mode-map
              ("C-l i" . lsp-ui-doc-glance))
  :config
  (setq lsp-ui-doc-enable t
        lsp-ui-doc-header t
        lsp-ui-doc-include-signature t
        lsp-ui-doc-position 'at-point
        lsp-ui-doc-border (face-foreground 'default)
        lsp-ui-doc-alignment 'window
        lsp-ui-doc-use-childframe t
        lsp-ui-doc-use-webkit nil
        lsp-ui-doc-delay 0.1
        lsp-ui-doc-show-with-cursor nil
        lsp-ui-doc-show-with-mouse nil
        lsp-ui-sideline-enable nil
        lsp-ui-imenu-enable nil
        lsp-ui-doc-max-height 20
        lsp-ui-doc-max-width 80
        lsp-ui-peek-enable t))
#+end_src

*** Treesit

Use tree-sitter for grokking language tokens for highlighting syntax.

#+begin_src emacs-lisp
(use-package treesit
  :ensure nil
  :mode (("\\.js\\'"  . js-ts-mode)
         ("\\.mjs\\'" . typescript-ts-mode)
         ("\\.mts\\'" . typescript-ts-mode)
         ("\\.cjs\\'" . typescript-ts-mode)
         ("\\.ts\\'"  . typescript-ts-mode)
         ("\\.tsx\\'" . tsx-ts-mode)
         ("\\.jsx\\'" . tsx-ts-mode)
         ("\\.json\\'" . json-ts-mode)
         ("Dockerfile$" . dockerfile-ts-mode)
         ("\\.yaml\\'" . yaml-ts-mode)
         ("\\.yml\\'" . yaml-ts-mode)
         ("\\.html\\'" . html-ts-mode)
         ("\\.css\\'" . css-ts-mode)
         ("\\.go\\'" . go-ts-mode)
         ("\\.ex\\'" . elixir-ts-mode)
         ("\\.exs\\'" . elixir-ts-mode)
         ("\\.rb\\'" . ruby-ts-mode)
         ("\\.rake\\'" . ruby-ts-mode)
         ("\\.ru\\'" . ruby-ts-mode)
         ("Gemfile\\'" . ruby-ts-mode)
         ("Rakefile\\'" . ruby-ts-mode)
         ("Capfile\\'" . ruby-ts-mode)
         ("\\.gemspec\\'" . ruby-ts-mode)
  )
  :preface
  (defun setup-install-grammars ()
    "Install Tree-sitter grammars if they are absent."
    (interactive)
    (dolist (grammar
             '((css . ("https://github.com/tree-sitter/tree-sitter-css" "v0.23.2"))
               (elixir . ("https://github.com/elixir-lang/tree-sitter-elixir" "v0.3.4" "src"))
               (javascript . ("https://github.com/tree-sitter/tree-sitter-javascript" "v0.25.0" "src"))
               (html . ("https://github.com/tree-sitter/tree-sitter-html" "v0.23.2"))
               (json . ("https://github.com/tree-sitter/tree-sitter-json" "v0.24.8"))
               (go . ("https://github.com/tree-sitter/tree-sitter-go" "v0.25.0"))
               (dockerfile . ("https://github.com/camdencheek/tree-sitter-dockerfile" "v0.2.0"))
               (tsx . ("https://github.com/tree-sitter/tree-sitter-typescript" "v0.23.2" "tsx/src"))
               (ruby . ("https://github.com/tree-sitter/tree-sitter-ruby" "v0.23.1"))
               (typescript . ("https://github.com/tree-sitter/tree-sitter-typescript" "v0.23.2" "typescript/src"))
               (yaml . ("https://github.com/ikatyang/tree-sitter-yaml" "v0.5.0"))))
      (unless (treesit-language-available-p (car grammar))
        (add-to-list 'treesit-language-source-alist grammar)
        (treesit-install-language-grammar (car grammar))))
    ;; Remapping major modes
    (dolist (mapping
             '((typescript-mode . typescript-ts-mode)
               (elixir-mode . elixir-ts-mode)
               (js-mode . js-ts-mode)
               (js-json-mode . json-ts-mode)
               (json-mode . json-ts-mode)
               (rjsx-mode . typescript-ts-mode)
               (css-mode . css-ts-mode)
               (html-mode . html-ts-mode)
               (sgml-mode . html-ts-mode)
               (yaml-mode . yaml-ts-mode)
               (go-mode . go-ts-mode)
               (toml-mode . go-ts-mode)
               (ruby-mode . ruby-ts-mode)
               (dockerfile-mode . dockerfile-ts-mode)))
      (add-to-list 'major-mode-remap-alist mapping)))
  :config
  (setup-install-grammars))
#+end_src

*** Company

Handles code completion

#+begin_src emacs-lisp
(use-package company
  :ensure t
  :after lsp-mode ;; ensures lsp-mode-map is defined
  :hook (prog-mode . company-mode)
  :init
  (setq company-minimum-prefix-length 2
        company-idle-delay 0.05
        company-tooltip-align-annotations t
        company-tooltip-limit 15
        company-show-numbers t
        company-require-match nil
        company-selection-wrap-around t)
  :config
  ;; Backend list
  (setq company-backends
        '((company-capf company-yasnippet)
          company-files
          company-keywords
          company-ispell
          company-dabbrev-code
          company-etags))
  ;; Keybindings
  (define-key company-active-map (kbd "<tab>") 'company-complete-selection)
  (define-key company-active-map (kbd "C-n") 'company-select-next)
  (define-key company-active-map (kbd "C-p") 'company-select-previous)
  (define-key lsp-mode-map (kbd "<tab>") 'company-indent-or-complete-common))

(use-package company-box
  :ensure t
  :defer t
  :hook (company-mode . company-box-mode))

(use-package company-quickhelp
  :ensure t
  :defer t
  :hook (company-mode . company-quickhelp-mode))
#+end_src

*** Golang

#+begin_src emacs-lisp
(use-package go-mode
  :ensure t
  :hook ((go-ts-mode . (lambda ()
                       (add-hook 'before-save-hook #'lsp-format-buffer t t)
                       (add-hook 'before-save-hook #'lsp-organize-imports t t)))))
#+end_src

*** Elixir

--> Handled with Treesitter.

** Features

*** Environment

Use direnv for this (make sure it is installed with your package manager).

#+begin_src emacs-lisp
(use-package envrc
  :ensure t
  :if (executable-find "direnv")
  :hook (after-init . envrc-global-mode))
#+end_src

*** Which-key

#+BEGIN_SRC emacs-lisp
(use-package which-key
  :ensure t
  :diminish
  :hook (after-init . which-key-mode)
  :config
  (setq which-key-idle-delay 0.5
        which-key-idle-secondary-delay nil))
#+END_SRC

*** Ace

Use ace-window to cycle through windows

#+BEGIN_SRC emacs-lisp
(use-package ace-window
  :ensure t
  :config (setq aw-dispatch-when-more-than 3)
  :bind ("M-o" . ace-window))
#+END_SRC

*** Ibuffer

#+BEGIN_SRC emacs-lisp
 (setq ibuffer-saved-filter-groups
            (quote (("Default"
                     ("Dired" (mode . dired-mode))
                     ("Org" (mode . org-mode))
                     ("Magit" (name . "^magit"))
                     ("Mail"  (name . "^\\*mu4e-main\\*$"))
                     ("Agenda" (or
                                  (name . "^\\*Calendar\\*$")
                                  (name . "^\\*Org Agenda\\*")))
                     ("LSP" (or
                              (name . "^\\*lsp-log\\*$")
                              (name . "^\\*lsp-documentation\\*$")
                              (name . "^\\*gopls\\*$")
                              (name . "^\\*gopls::stderr\\*$")))
                      ("Emacs" (or
                               (name . "^\\*scratch\\*$")
                               (name . "^\\*Async-native-compile-log\\*$")
                               (name . "^\\*Native-compile-Log\\*$")
                               (name . "^\\*mu4e-last-update\\*$")
                               (name . "^\\*trace*")
                               (name . "^\\*Messages\\*$")))))))

  (add-hook 'ibuffer-mode-hook
            (lambda ()
              (ibuffer-switch-to-saved-filter-groups "Default")))
#+END_SRC

*** Activities

#+begin_src emacs-lisp
(use-package activities
  :ensure t
  :init
  (activities-mode)
  (activities-tabs-mode)
  (setq edebug-inhibit-emacs-lisp-mode-bindings t)

  :bind
  (("C-x C-a C-n" . activities-new)
   ("C-x C-a C-d" . activities-define)
   ("C-x C-a C-a" . activities-resume)
   ("C-x C-a C-s" . activities-suspend)
   ("C-x C-a C-k" . activities-kill)
   ("C-x C-a RET" . activities-switch)
   ("C-x C-a b" . activities-switch-buffer)
   ("C-x C-a g" . activities-revert)
   ("C-x C-a l" . activities-list))

  :config
  (defun my/activities-switch-to-scratch (&rest _)
    "Switch to *scratch* buffer after creating a new activity."
    (switch-to-buffer "*scratch*"))

  ;; Add post advice to activities-new
  (advice-add 'activities-new :after #'my/activities-switch-to-scratch))
#+end_src

#+begin_src emacs-lisp
(use-package tab-bar
  :ensure nil
  :init
  (setq tab-bar-show nil)
  :config
  (tab-bar-mode 1)

  (defface my/tab-name-face
    '((t (:inherit mode-line-buffer-id :foreground "#ffaa00")))
    "Face for tab name in the mode line.")

  (defun my/tab-bar-tab-name ()
    (let ((name (alist-get 'name (tab-bar--current-tab))))
      (propertize (format " 📁 %s " name) 'face 'my/tab-name-face)))

  ;; Only append once to avoid duplication
  (unless (member '(:eval (my/tab-bar-tab-name)) mode-line-format)
    (setq-default
     mode-line-format
     (append mode-line-format
             '((:eval (my/tab-bar-tab-name))))))

  ;; Keybindings
  (global-set-key (kbd "C-c t n") #'tab-bar-new-tab)
  (global-set-key (kbd "C-c t k") #'tab-bar-close-tab)
  (global-set-key (kbd "C-c t o") #'tab-bar-switch-to-tab)
  (global-set-key (kbd "C-c t r") #'my/rename-current-tab))
#+end_src

*** Encryption

EasyPG is used for encryption. More info
([[https://www.emacswiki.org/emacs/EasyPG]]).

GPG_AGENT_INFO environment variable is assumed to be loaded (in Mac OS X,
implement S. Purcell's [[exec-path-from-shell][exec-path-from-shell]]. In GNU/Linux, the variable is fed
to the daemon started from a systemd service definition.

#+BEGIN_SRC emacs-lisp
(setq epg-gpg-program "gpg"
      epa-file-inhibit-auto-save t
      epa-file-encrypt-to '("manuel@manuel.is")      ;; Hack to make org-roam capture
      epa-file-select-keys 1                         ;; pick up automatically the key with which to encrypt the note. See https://superuser.com/questions/1204820/emacs-easypg-asks-what-key-to-use-although-epa-file-encrypt-to-already-specified
      epa-pinentry-mode 'loopback)
#+END_SRC

For credentials, use `auth-source-pass`, included in Emacs 26. See
more [[https://www.gnu.org/software/emacs/manual/html_mono/auth.html][here]].

#+begin_src emacs-lisp
(use-package auth-source
  :no-require
  :config (setq auth-sources '("~/.authinfo.gpg")))
#+end_src

*** Tramp mode

Use `tramp` to shell into other machines.

#+BEGIN_SRC emacs-lisp
(use-package tramp
  :ensure t
  :defer t
  :config
  (tramp-set-completion-function "ssh" '((tramp-parse-sconfig "/etc/ssh_config") (tramp-parse-sconfig "~/.ssh/config"))))
#+END_SRC

*** Smart parens

Use smart parens when writing parenthesis to not let any parethesis unmatched.

#+BEGIN_SRC emacs-lisp
(use-package smartparens
  :ensure t
  :diminish smartparens-mode
  :init (smartparens-global-mode t))
#+END_SRC

*** Projectile

Use Projectile to manage projects as an entity.

#+BEGIN_SRC emacs-lisp
(use-package projectile
  :ensure t
  :delight '(:eval (concat " " (projectile-project-name)))
  :defer t
  :init
  (setq-default
   projectile-cache-file (expand-file-name ".projectile-cache" user-emacs-directory)
   projectile-keymap-prefix (kbd "C-c C-p")
   projectile-known-projects-file (expand-file-name
                                   ".projectile-bookmarks" user-emacs-directory))
  :config
  (projectile-mode 1)
  (setq-default
   projectile-indexing-method 'alien
   projectile-globally-ignored-modes '("org-mode" "org-agenda-mode")
   projectile-globally-ignored-file-suffixes '(".gpg")
   projectile-completion-system 'default ;; Uses selectrum (based on Emacs API `completing-read`
   projectile-enable-caching 'nil ;; https://emacs.stackexchange.com/a/2169
   projectile-mode-line '(:eval (projectile-project-name)))
   (add-hook 'org-agenda-mode-hook (lambda () (projectile-mode -1)))
   (add-hook 'org-mode-hook (lambda () (projectile-mode -1))))
#+END_SRC

*** Treemacs

Use `treemacs` to open a side window displaying the folder structure of a
project or a directory, á la Eclipse or other common IDEs.

#+BEGIN_SRC emacs-lisp
(use-package treemacs
  :ensure t
  :init (defvar treemacs-no-load-time-warnings t)
  :defer t
  :config
  (setq treemacs-follow-after-init t
        treemacs-width 65
        treemacs-indentation 1
        treemacs-recenter-after-file-follow nil
        treemacs-silent-refresh t
        treemacs-silent-filewatch t
        treemacs-change-root-without-asking t
        treemacs-sorting 'alphabetic-asc
        treemacs-show-hidden-files t
        treemacs-never-persist nil
        treemacs-is-never-other-window nil
        treemacs-indentation-string (propertize " ǀ " 'face 'font-lock-comment-face)
        treemacs-follow-mode t
        treemacs-filewatch-mode t
        treemacs-fringe-indicator-mode t
        treemacs-eldoc-display t)
  :bind
  (([f8] . treemacs)
   ("C-c f" . treemacs-select-window)))

(use-package treemacs-projectile
  :ensure t
  :after treemacs projectile
  :bind
  (("C-c o p" . treemacs-projectile)))
#+END_SRC

*** Code folding

Fold code. I found yafolding simplier to use than e.g.: origami and
more feature complete than treesit-fold.
#+BEGIN_SRC emacs-lisp
(use-package yafolding
  :ensure t
  :hook ((prog-mode text-mode) . yafolding-mode)
  :bind (:map yafolding-mode-map
              ("M-n" . yafolding-toggle-element)
              ("M-m" . yafolding-toggle-all)))
#+END_SRC

*** Verb

Use [[https://github.com/federicotdn/verb][verb]] to explore APIs as an alternative for the defunct [[https://github.com/pashky/restclient.el][restclient]].

#+begin_src emacs-lisp
(use-package verb
  :ensure t
  :after org ;; Ensure verb is loaded after org
  :config
  ;; Map verb-command-map to "C-c C-r" in org-mode
  (define-key org-mode-map (kbd "C-c C-r") verb-command-map))
#+end_src

*** Magit

Let's put a nice modeline. Stolen from [[https://emacs.stackexchange.com/a/61318/14683][here]].

#+begin_src emacs-lisp
(advice-add #'vc-git-mode-line-string :filter-return #'my-replace-git-status)
(defun my-replace-git-status (tstr)
  (let* ((tstr (replace-regexp-in-string "Git" "" tstr))
         (first-char (substring tstr 0 1))
         (rest-chars (substring tstr 1)))
    (cond
     ((string= ":" first-char) ;;; Modified
      (replace-regexp-in-string "^:" "⚡️" tstr))
     ((string= "-" first-char) ;; No change
      (replace-regexp-in-string "^-" "✔️" tstr))
     (t tstr))))
#+end_src

Magit is love for Emacs.

#+BEGIN_SRC emacs-lisp
(use-package magit
  :ensure t
  :defer t
  :config
    (setq magit-log-arguments '("-n256" "--graph" "--decorate" "--color"))
  :bind (("C-x g" . magit-status))
  :init
  (setq-default
   magit-auto-revert-mode nil
   magit-refs-show-commit-count 'all
   magit-section-show-child-count t
   magit-log-section-commit-count 15))
#+END_SRC

Configuring forge
#+begin_src emacs-lisp
(use-package forge
  :ensure t
  :after magit)
#+end_src

Use github-review along with forge. See more [[https://github.com/charignon/github-review][here]].

#+begin_src emacs-lisp
(use-package github-review
  :ensure t
  :defer t
  :config
  (setq
   github-review-reply-inline-comments t
   github-review-view-comments-in-code-lines t
   github-review-view-comments-in-code-lines-outdated t))
#+end_src

*** Flycheck

On-the-fly syntax checking

#+begin_src emacs-lisp
(use-package flycheck
  :ensure t
  :defer t
  :diminish
  :bind (:map flycheck-mode-map
    ("M-s-n" . flycheck-next-error) ; optional but recommended error navigation
    ("M-s-p" . flycheck-previous-error))
  :init (global-flycheck-mode)
  :config
  (setq flycheck-check-syntax-automatically '(save mode-enabled)))

(use-package flycheck-pos-tip
  :ensure t
  :defer t
  :after flycheck
  :config
  (setq flycheck-display-errors-function #'flycheck-pos-tip-error-messages))
#+end_src

*** Vertico + Orderless + Marginalia + Consult

[[https://github.com/minad/vertico][Vertico]] is an interesting alternative to Ivy + Swiper and a substitute of Selectrum

#+begin_src emacs-lisp
(use-package vertico
  :ensure t
  :bind (:map vertico-map
         ("C-n" . vertico-next)
         ("C-p" . vertico-previous)
         ("C-f" . vertico-exit)
         :map minibuffer-local-map
         ("M-h" . backward-kill-word))
  :custom
  (vertico-cycle t)
  :init
  (vertico-mode)
  :config
  (setq completion-styles '(basic substring partial-completion flex))
  (setq read-file-name-completion-ignore-case t
        read-buffer-completion-ignore-case t
        completion-ignore-case t))
#+end_src

[[https://github.com/oantolin/orderless][Orderless]] for giving order to Vertico's

#+begin_src emacs-lisp
(use-package orderless
  :ensure t
  :init
  ;; Configure a custom style dispatcher (see the Consult wiki)
  ; (setq orderless-style-dispatchers '(+orderless-dispatch)
  ;       orderless-component-separator #'orderless-escapable-split-on-space)
  (setq completion-styles '(orderless basic)
        completion-category-defaults nil
        completion-category-overrides '((file (styles partial-completion)))))
#+end_src

[[https://github.com/minad/marginalia/][Marginalia]] is an awesome package to give context to the mini-buffer list

#+begin_src emacs-lisp
(use-package marginalia
  :ensure t
  ;; Either bind `marginalia-cycle` globally or only in the minibuffer
  :bind (:map minibuffer-local-map
         ("M-A" . marginalia-cycle))
  :init (marginalia-mode))
#+end_src

[[https://github.com/minad/consult][Consult]] provides practical commands based on the completion functionality

#+begin_src emacs-lisp
(use-package consult
  :ensure t
  ;; Replace bindings. Lazily loaded due by `use-package'.
  :bind (;; C-c bindings (mode-specific-map)
         ("C-c m" . consult-mode-command)
         ;; Other custom bindings
         ("M-y" . consult-yank-pop)                ;; orig. yank-pop
         ("<help> a" . consult-apropos)            ;; orig. apropos-command
         ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
         ;; M-g bindings (goto-map)
         ("M-g e" . consult-compile-error)
         ("M-g f" . consult-flycheck)               ;; Alternative: consult-flymake
         ("M-g g" . consult-goto-line)             ;; orig. goto-line
         ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
         ("M-g o" . consult-outline)               ;; Alternative: consult-org-heading
         ("M-g m" . consult-mark)
         ("M-g k" . consult-global-mark)
         ("M-g i" . consult-imenu)
         ("s-r" . consult-ripgrep)
         ("s-g" . consult-grep)
         ("s-s" . consult-line-multi)
         ("C-s" . consult-line)
         ("s-a" . consult-find)
         ("M-g I" . consult-imenu-multi))

  ;; The :init configuration is always executed (Not lazy)
  :init

  ;; Optionally configure the register formatting. This improves the register
  ;; preview for `consult-register', `consult-register-load',
  ;; `consult-register-store' and the Emacs built-ins.
  (setq register-preview-delay 0
        register-preview-function #'consult-register-format)

  ;; Optionally tweak the register preview window.
  ;; This adds thin lines, sorting and hides the mode line of the window.
  (advice-add #'register-preview :override #'consult-register-window)

  ;; Optionally replace `completing-read-multiple' with an enhanced version.
  ;;(advice-add #'completing-read-multiple :override #'consult-completing-read-multiple)

  ;; Use Consult to select xref locations with preview
  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref)

  ;; Configure other variables and modes in the :config section,
  ;; after lazily loading the package.
  :config

  ;; Optionally configure preview. The default value
  ;; is 'any, such that any key triggers the preview.
  ;; (setq consult-preview-key 'any)
  ;; (setq consult-preview-key "M-.")
  ;; (setq consult-preview-key '("S-<down>" "S-<up>"))
  ;; For some commands and buffer sources it is useful to configure the
  ;; :preview-key on a per-command basis using the `consult-customize' macro.
  (consult-customize
   consult-theme :preview-key '(:debounce 0.2 any)
   consult-ripgrep consult-git-grep consult-grep
   consult-bookmark consult-recent-file consult-xref
   consult--source-bookmark consult--source-file-register
   consult--source-recent-file consult--source-project-recent-file
   ;; :preview-key "M-."
   :preview-key '(:debounce 0.4 any))

  ;; Optionally configure the narrowing key.
  ;; Both < and C-+ work reasonably well.
  (setq consult-narrow-key "<") ;; (kbd "C-+")

  ;; Optionally make narrowing help available in the minibuffer.
  ;; You may want to use `embark-prefix-help-command' or which-key instead.
  ;; (define-key consult-narrow-map (vconcat consult-narrow-key "?") #'consult-narrow-help)

  ;;;; 4. projectile.el (projectile-project-root)
  (autoload 'projectile-project-root "projectile")
  (setq consult-project-function (lambda (_) (projectile-project-root)))
)
#+end_src

*** YASnippet

A template system for filling in the knowledge blanks ;) Set hook per language

For it to work, the host must have installed yasnippet and
yasnippet-snippets. Note the folders stored in yas-snippet-dirs.
#+begin_src emacs-lisp
(use-package yasnippet
  :ensure t
  :hook
  ((prog-mode . yas-minor-mode)
   (text-mode . yas-minor-mode))
  :init
  (setq yas-verbosity 1
        yas-wrap-around-region t
        yas-snippet-dirs '("~/.emacs.d/snippets"
                           "/usr/share/yasnippet-snippets"))
  :config
  (define-key yas-keymap (kbd "TAB") 'yas-next-field)
  (define-key yas-keymap (kbd "<tab>") 'yas-next-field)
  (define-key yas-keymap (kbd "S-TAB") 'yas-prev-field)
  (global-set-key (kbd "C-c y") #'yas-insert-snippet))

(use-package yasnippet-snippets
  :ensure t
  :after yasnippet)
#+end_src

*** Flyspell

Use flyspell for highlighting and correcting spelling mistakes.

#+begin_src emacs-lisp
(use-package flyspell
  :ensure t
  :diminish
  :defer t
  :hook (text-mode . flyspell-mode)
  :custom
    (flyspell-correct-interface #'flyspell-correct-dummy)
    (ispell-quietly t))
#+end_src

*** Ripgrep

`ripgrep` is a fast grep tool built in Rust. [[https://github.com/dajva/rg.el][rg]] is a `ripgrep`
frontend for Emacs.

#+begin_src emacs-lisp
(use-package rg
  :ensure t
  :init (rg-enable-default-bindings))
#+end_src

*** Diminish

Manages modeline for minor modes

#+begin_src emacs-lisp
(use-package diminish
  :ensure t
  :diminish auto-fill-mode
  :diminish eldoc-mode
  :diminish org-indent-mode)
#+end_src

*** Delight

Manages modeline for minor and major modes

#+begin_src emacs-lisp
(use-package delight
  :ensure t)
#+end_src

*** UUID

Provide UUID generation support (for all standards) inside Emacs

#+begin_src emacs-lisp
(use-package uuidgen
  :ensure t
  :defer t)
#+end_src

*** Edit-server
[[https://github.com/stsquad/emacs_chrome][edit-server]] is a feature that works in conjunction with browsers' plugins
(depending on browser) to prompt an Emacs frame when editing text areas on the
browser.

#+begin_src emacs-lisp
(use-package edit-server
  :ensure t
  :commands edit-server-start
  :init (if after-init-time
              (edit-server-start)
            (add-hook 'after-init-hook
                      #'(lambda() (edit-server-start))))
  :config (setq edit-server-new-frame-alist
                '((name . "Edit with Emacs FRAME")
                  (top . 200)
                  (left . 200)
                  (width . 80)
                  (height . 25)
                  (minibuffer . t)
                  (menu-bar-lines . t)
                  (window-system . pgtk))))
#+end_src

*** Dictionaries

Setup dictionaries (in Linux only). It needs of `dictionaries-common` and
`dictd` in Debian Bookworm.

Some dictionaries installed:

- dict-devil
- dict-jargon
- dict-vera
- dict-wn

Besides this, make sure to enable dictd system unit

`$ sudo systemctl enable dictd`

#+begin_src emacs-lisp
(use-package dictionary
  :ensure t
  :bind (([f5] . dictionary-search) ([f6] . dictionary-lookup-definition))
  :config
  (setq dictionary-use-single-buffer t)
  (setq dictionary-server "localhost"))
#+end_src

A thesaurus for synonyms

#+begin_src emacs-lisp
(use-package powerthesaurus
  :ensure t
  :defer t
  :bind (([f7] . powerthesaurus-lookup-dwim))
)
#+end_src

Detect the operating system and set ispell-program-name accordingly

#+begin_src emacs-lisp
(cond
 ((eq system-type 'darwin) ; macOS
  (setq ispell-program-name "/usr/local/bin/ispell"))
 ((eq system-type 'gnu/linux) ; Linux
  (setq ispell-program-name "/usr/bin/ispell")))
#+end_src

*** Emoji

#+begin_src emacs-lisp
(use-package emojify
  :ensure t
  :config
  (when (member "Noto Color Emoji" (font-family-list))
    (set-fontset-font
     t 'symbol (font-spec :family "Noto Color Emoji") nil 'prepend))
  (setq emojify-display-style 'github)
  (setq emojify-emoji-styles '(github)))
#+end_src

#+begin_src emacs-lisp
(use-package company-emojify
  :ensure t
  :config
    (setq company-emojify-emoji-styles '(github)))

(with-eval-after-load 'company
  (add-to-list 'company-backends 'company-emojify))
#+end_src

*** Terminal
I use vterm as a terminal for Emacs

#+begin_src emacs-lisp
(use-package vterm
  :ensure t
  :bind (:map vterm-mode-map ("C-y" . vterm-yank))
  :config (setq vterm-max-scrollback 100000))
#+end_src

#+begin_src emacs-lisp

(use-package vterm-toggle
  :ensure t
  :bind (([f2] . vterm-toggle)
         ([C-f2] . vterm-toggle-cd))
  :config
  ;; Advice to set vterm-environment before opening vterm-toggle
  (defun my/vterm-toggle-set-env (orig-fun &rest args)
    "Ensure `vterm-toggle` uses Emacs's PATH environment."
    (let ((vterm-environment (list (concat "PATH=" (getenv "PATH")))))
      (apply orig-fun args)))
  (advice-add 'vterm-toggle :around #'my/vterm-toggle-set-env)
  (advice-add 'vterm-toggle-cd :around #'my/vterm-toggle-set-env))
#+end_src

*** Expand region

See [[https://github.com/magnars/expand-region.el][here]]

#+begin_src emacs-lisp
(use-package expand-region
  :ensure t
  :bind ("C-d" . er/expand-region))

(setq pending-delete-mode t)
#+end_src

*** Multiple cursors

Again, Magnars at it. See [[https://github.com/magnars/multiple-cursors.el][here]].

#+begin_src emacs-lisp
(use-package multiple-cursors
  :ensure t)
#+end_src

*** Casual

See intro to Casual in this EmacsConf video:
https://www.youtube.com/watch?v=-eMmmAKcFR4

#+begin_src emacs-lisp
(use-package casual
  :ensure t)
(keymap-global-set "C-o" #'casual-editkit-main-tmenu)
(add-hook 'dired-mode-hook
          (lambda ()
            (local-set-key (kbd "C-o") #'casual-dired-tmenu)))
(add-hook 'org-agenda-mode-hook
          (lambda ()
            (local-set-key (kbd "C-o") #'casual-agenda-tmenu)))
(keymap-set help-mode-map "C-o" #'casual-help-tmenu)
(add-hook 'csv-mode-hook
          (lambda ()
            (local-set-key (kbd "C-o") #'casual-csv-tmenu)))
(add-hook 'makefile-mode-hook
          (lambda ()
            (local-set-key (kbd "C-o") #'casual-make-tmenu)))
(keymap-set calendar-mode-map "C-o" #'casual-calendar-tmenu)
(add-hook 'ediff-keymap-setup-hook
          (lambda ()
            (keymap-set ediff-mode-map "C-o" #'casual-ediff-tmenu)))
(keymap-set ibuffer-mode-map "C-o" #'casual-ibuffer-tmenu)
(keymap-set ibuffer-mode-map "F"   #'casual-ibuffer-filter-tmenu)
(keymap-set ibuffer-mode-map "s"   #'casual-ibuffer-sortby-tmenu)
(keymap-set Info-mode-map "C-o" #'casual-info-tmenu)
(keymap-set isearch-mode-map "C-o" #'casual-isearch-tmenu)
(add-hook 'reb-mode-hook
          (lambda ()
            (local-set-key (kbd "C-o") #'casual-re-builder-tmenu)))
(add-hook 'calc-mode-hook
          (lambda ()
            (local-set-key (kbd "C-o") #'casual-calc-tmenu)))
(with-eval-after-load 'calc
  (keymap-set calc-mode-map "C-o" #'casual-calc-tmenu)
  (keymap-set calc-alg-map  "C-o" #'casual-calc-tmenu))
(keymap-set compilation-mode-map "C-o" #'casual-compile-tmenu)
(keymap-set grep-mode-map "C-o" #'casual-compile-tmenu)
#+end_src

*** Timezones

#+begin_src emacs-lisp
(use-package time-zones
  :ensure t)
#+end_src


** Org

*** Agenda files
Adding org files for agenda

#+BEGIN_SRC emacs-lisp
(if (eq system-type 'darwin)
    (setq org-directory "/Users/spav/Dropbox/org/documents"
          org-default-notes-file "/Users/spav/Dropbox/org/documents/refile.org.gpg")
  (setq org-directory "/home/manuel/Dropbox/org/documents"
        org-default-notes-file "/home/manuel/Dropbox/org/documents/refile.org.gpg"))
(require 'find-lisp)
(setq org-agenda-files
  (find-lisp-find-files org-directory "\.org.gpg"))
#+END_SRC

*** Main org configs

The thick of it

#+BEGIN_SRC emacs-lisp
(use-package org
  :ensure t
  :init
  (add-to-list 'auto-mode-alist '("\\.txt\\'" . org-mode))
  (add-to-list 'auto-mode-alist '(".*/[0-9]*$" . org-mode))
  :hook (org-mode . auto-fill-mode)
  :hook (org-journal-mode . auto-fill-mode)
  :bind (("C-c l" . org-store-link)
         ("C-c n" . org-capture)
         ("C-c a" . org-agenda)
         ("C-M-<return>" . org-insert-item)
         ("C-c C-x i" . org-clock-in)
         ("C-c C-x o" . org-clock-out))
  :config
  (setq org-support-shift-select t
        org-return-follows-link t 
        org-duration-format 'h:mm
        org-hide-emphasis-markers t
        org-outline-path-complete-in-steps nil
        org-src-fontify-natively t
        org-src-tab-acts-natively t
        org-confirm-babel-evaluate nil
        org-log-done t
        org-refile-targets '((nil :maxlevel . 9) (org-agenda-files :maxlevel . 9))
        org-refile-use-outline-path t
        org-outline-path-complete-in-steps nil
        org-indirect-buffer-display 'current-window
        org-fast-tag-selection-include-todo t
        org-use-fast-todo-selection t
        org-startup-indented t
        org-treat-S-cursor-todo-selection-as-state-change nil
        org-startup-with-inline-images t
        org-modules (append org-modules '(org-habit)))
  (require 'org-tempo) ;; Make code blocks the old way with `<s TAB`
  (font-lock-add-keywords
   'org-mode `(("^\\*+ \\(TODO\\) "
                (1 (progn (compose-region (match-beginning 1) (match-end 1) "⚑") nil)))
               ("^\\*+ \\(PROGRESSING\\) "
                (1 (progn (compose-region (match-beginning 1) (match-end 1) "⚐") nil)))
               ("^\\*+ \\(CANCELLED\\) "
                (1 (progn (compose-region (match-beginning 1) (match-end 1) "✘") nil)))
               ("^\\*+ \\(DONE\\) "
                (1 (progn (compose-region (match-beginning 1) (match-end 1) "✔") nil)))))
  (setq org-todo-keywords '((sequence "TODO(t)" "PROGRESSING(p)" "|" "DONE(d)")
                              (sequence "WAITING(w@/!)" "HOLD(h@/!)" "|" "CANCELLED(c@/!)"))
          org-todo-keyword-faces
          '(("TODO" :foreground "red" :weight bold)
            ("PROGRESSING" :foreground "deep sky blue" :weight bold)
            ("DONE" :foreground "forest green" :weight bold)
            ("WAITING" :foreground "orange" :weight bold)
            ("HOLD" :foreground "magenta" :weight bold)
            ("CANCELLED" :foreground "forest green" :weight bold)))
     (setq org-agenda-custom-commands
      '(("w" "Work agenda"
         ((agenda "")
          (tags-todo "work")))))
  (setq org-todo-state-tags-triggers
          (quote (("CANCELLED" ("CANCELLED" . t))
                  ("WAITING" ("WAITING" . t))
                  ("HOLD" ("WAITING") ("HOLD" . t))
                  (done ("WAITING") ("HOLD"))
                  ("TODO" ("WAITING") ("CANCELLED") ("HOLD"))
                  ("NEXT" ("WAITING") ("CANCELLED") ("HOLD"))
                  ("DONE" ("WAITING") ("CANCELLED") ("HOLD")))))
    (define-key org-mode-map [remap org-return] (lambda () (interactive)
                                                  (if (org-in-src-block-p)
                                                      (org-return) (org-return-indent)))))
#+END_SRC

*** Journaling

Org journaling

#+BEGIN_SRC emacs-lisp
(use-package org-journal
  :ensure t
  :defer t
  :init
  (setq org-journal-prefix-key "C-c j")
  :config
  (setq org-journal-date-format "%A, %d %B %Y"
        org-journal-file-format "%Y%m%d.org.gpg"
        org-journal-file-header "# -*- mode:org; epa-file-encrypt-to: (\"manuel@manuel.is\") -*-")
  :bind* ("C-c C-j" . org-journal-new-entry))
#+END_SRC


#+begin_src emacs-lisp
(if (eq system-type 'darwin)
    (setq org-journal-dir "/Users/spav/Dropbox/org/documents/diary/")
  (setq org-journal-dir "/home/manuel/Dropbox/org/documents/diary/"))
#+end_src

*** Org-template

Org-template custom configurations

#+BEGIN_SRC emacs-lisp
(defvar org-capture-templates
  '(
    ("t" "Inbox recipient."
     entry 
     (file+headline org-default-notes-file "Inbox")
     (file "~/.emacs.d/org-templates/schedule.orgcaptmpl"))
    ("l" "Link: Something interesting?"
     entry
     (file+headline org-default-notes-file "Links")
     (file "~/.emacs.d/org-templates/links.orgcaptmpl"))
    ("i" "Idea came up." 
     entry 
     (file+headline org-default-notes-file "Ideas")
     "*** %? \n Captured on %U")))
#+END_SRC

*** Meeting note taking 

(source: [[https://github.com/howardabrams/dot-files/][Howard Abrams' Github]])

#+BEGIN_SRC emacs-lisp
(defun meeting-notes ()
  "Call this after creating an ´org-mode´ heading.
After calling this function, call meeting-done to reset the environment."
  (interactive)
  (outline-mark-subtree)
  (narrow-to-region (region-beginning) (region-end))
  (deactivate-mark)
  (delete-other-windows)
  (fringe-mode 0)
  (message "When finished taking your notes, run meeting-done."))

(defun meeting-done ()
  "Attempt to undo the effects of taking meeting notes."
  (interactive)
  (widen)
  (fringe-mode 1))
#+END_SRC

*** Bullets!

#+BEGIN_SRC emacs-lisp
(use-package org-bullets
  :ensure t
  :after org
  :hook
  (org-mode . (lambda () (org-bullets-mode 1))))
#+END_SRC

*** Calendar

Calendar modifications (Finnish calendar, etc)

#+BEGIN_SRC emacs-lisp
(use-package suomalainen-kalenteri
  :ensure t
  :defer t
  :after org
  :config
  (setq calendar-date-style 'european
        calendar-latitude 60.1
        calendar-longitude 24.9
        calendar-week-start-day 1
        calendar-today-visible-hook 'calendar-mark-today
        calendar-holidays suomalainen-kalenteri))
#+END_SRC

*** Org-agenda configs

Some org-agenda specific configs.

#+BEGIN_SRC emacs-lisp
(setq org-agenda-use-tag-inheritance nil
      org-agenda-ignore-drawer-properties '(effort appt category)
      org-agenda-dim-blocked-tasks nil
      org-agenda-tags-column -55
      org-log-into-drawer t)
#+END_SRC

*** Org-habits

Using org habits to track repeating tasks.

#+begin_src emacs-lisp
(setq org-habit-show-habits-only-for-today nil
      org-habit-graph-column 60
      org-habit-show-all-today t
      org-habit-show-following-days 10
      org-habit-preceding-days 10
      org-habit-show-habits t)
#+end_src

*** Ditaa and org-babel

Ditaa is a nice (Java) tool to generate images from ASCII. More info:
https://github.com/stathissideris/ditaa

#+begin_src emacs-lisp
(org-babel-do-load-languages 'org-babel-load-languages '(
                                                         (python . t)
                                                         (shell . t)
                                                         (sql . t)
                                                         (ditaa . t)))
(setq org-ditaa-jar-path "/usr/bin/ditaa")
#+end_src

SQL on Org files (Babel)

#+begin_src emacs-lisp
(setq sql-mysql-options '("-A" "--default-character-set=utf8"))
(setq org-confirm-babel-evaluate
      (lambda (lang body)
        (not (string= lang "sql"))))
#+end_src

*** Bindings

#+begin_src emacs-lisp
(define-key org-mode-map (kbd "s-<return>") 'org-meta-return)
(define-key org-mode-map (kbd "C-s-<return>") 'org-insert-heading-respect-content)
(define-key org-mode-map (kbd "C-s-i") 'org-promote-subtree)
(define-key org-mode-map (kbd "C-s-k") 'org-demote-subtree)
(define-key org-mode-map (kbd "C-s-j") 'org-do-promote)
(define-key org-mode-map (kbd "C-s-l") 'org-do-demote)
#+end_src


** Keybindings

Open this file

#+begin_src emacs-lisp
(define-key global-map (kbd "ESC ESC c")(lambda() (interactive)(find-file "~/.emacs.d/config.org")))
#+end_src

Ibuffer

#+begin_src emacs-lisp
(global-set-key (kbd "C-x C-b") 'ibuffer)
#+end_src

Use `C-x C-0` to restore font size.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-+") (lambda ()
                              (interactive)
                              (set-face-attribute 'default nil :height
                                                  (+ (face-attribute 'default :height) 10))))
(global-set-key (kbd "C--") (lambda ()
                              (interactive)
                              (set-face-attribute 'default nil :height
                                                  (- (face-attribute 'default :height) 10))))
(global-set-key (kbd "C-0") (lambda ()
                              (interactive)
                              (set-face-attribute 'default nil :height 140)))
#+END_SRC

Bind backward-kill-word to C-w

#+begin_src emacs-lisp
(global-set-key (kbd "C-w") 'backward-kill-word)
#+end_src

Global Copy & Paste in Unix

#+begin_src emacs-lisp
;; Copy to clipboard
(defun copy-to-clipboard ()
  "Copies selection to x-clipboard."
  (interactive)
  (if (display-graphic-p)
      (progn
        (message "Yanked region to x-clipboard!")
        (call-interactively 'clipboard-kill-ring-save))
    (if (region-active-p)
        (progn
          (shell-command-on-region (region-beginning) (region-end) "xsel -i -b")
          (message "Yanked region to clipboard!")
          (deactivate-mark))
      (message "No region active; can't yank to clipboard!"))))
 ;; Paste from clipboard
(defun paste-from-clipboard ()
  "Paste from clipboard."
  (interactive)
  (if (display-graphic-p)
      (progn
        (clipboard-yank)
        (message "graphics active"))
    (insert (shell-command-to-string "xsel -o -b"))))
#+end_src

Miscellaneous keybindings

#+begin_src emacs-lisp
(define-key global-map (kbd "s-d") 'projectile-find-dir)       ;; Find folder in project
(define-key global-map (kbd "s-f") 'projectile-find-file)      ;; Find file in project
(define-key global-map (kbd "s-p") 'projectile-switch-project) ;; Switch project
(define-key global-map (kbd "s-m") 'magit-status)              ;; Magit status
(define-key global-map (kbd "s-e") 'elfeed) ;; Elfeed
#+end_src

Resize window

#+begin_src emacs-lisp
(define-key global-map (kbd "M-s-<left>") 'shrink-window-horizontally)
(define-key global-map (kbd "M-s-<right>") 'enlarge-window-horizontally)
(define-key global-map (kbd "M-s-<down>") 'shrink-window)
(define-key global-map (kbd "M-s-<up>") 'enlarge-window)
#+end_src

Insert emoji globally

#+begin_src emacs-lisp
(global-set-key (kbd "C-ö") 'emojify-insert-emoji)
#+end_src

Comment DWIM

#+begin_src emacs-lisp
(global-set-key (kbd "C-;") 'comment-dwim)
#+end_src


** Custom


Add week numbers to calendar

Taken from https://www.emacswiki.org/emacs/CalendarWeekNumbers

NOTE: Only in Finland such a thing is needed as week numbers...

#+begin_src emacs-lisp
(copy-face font-lock-constant-face 'calendar-iso-week-face)
(set-face-attribute 'calendar-iso-week-face nil
                    :height 0.7 :foreground "salmon")
(setq calendar-intermonth-text
      '(propertize
        (format "%2d"
                (car
                 (calendar-iso-from-absolute
                  (calendar-absolute-from-gregorian (list month day year)))))
        'font-lock-face 'calendar-iso-week-face))
#+end_src


#+begin_src emacs-lisp
(defun treesit-show-parser-used-at-point ()
  "Shows treesit parser used at point."
  (interactive)
  (if (and (fboundp 'treesit-available-p)
           (treesit-available-p))
      (message (format "%s" (treesit-language-at (point))))
    (message "treesit is not available")
  )
)
#+end_src
