(add-hook 'go-mode-hook 'go-eldoc-setup)
(add-hook 'before-save-hook #'gofmt-before-save)
(add-hook 'go-mode-hook 'flycheck-mode)
(add-hook 'go-mode-hook 'dumb-jump-mode)
(add-hook 'go-mode-hook 'company-mode)
(global-company-mode t)
(add-hook 'go-mode-hook (lambda ()
 (set (make-local-variable 'company-backends) '(company-go))
 (company-mode)))
